services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    volumes:
      - ./backend:/app
    depends_on:
      - db

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - api

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
