services:
  db:
    image: postgres:15
    container_name: betterreads-db
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    volumes:
      - ./backend:/app
    depends_on:
      - db

volumes:
  pgdata:
